### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'html' of undefined

### ISSUE THREAD

**Issue by ryanwake01** [HugoGiraudel/Countdown.js#19]
I am getting this error when loading pages transitions. 
Site: http://ryanwake.com/gramacy/   

I have also noticed this message in the console that I am not quite sure what it means. (XHR finished loading: GET "http://ryanwake.com/gramacy/r_packages/reglogit/".)

Screenshot: https://www.dropbox.com/s/ezxi4lzwp7mdg1u/Screenshot%202015-03-03%2015.42.53.png?dl=0

I am using Chrome on a Mac if that matters.

**Comment by HugoGiraudel** [comment]
Hey. I can't see any error on your site and the file does not exist anymore in Dropbox.

**Comment by ryanwake01** [comment]
Hugo, 

I apologize. I had to upload a version of the site for the client to review without the proper CSS in place. It is current now. http://ryanwake.com

Also, attached is the image. 
![screenshot 2015-03-09 16 21 09](https://cloud.githubusercontent.com/assets/5551191/6564658/9fbf9522-c678-11e4-8db7-d0d741618d68.png)

**Comment by HugoGiraudel** [comment]
Still can't see the error on your site.

**Comment by ryanwake01** [comment]
It seems that if you scroll down, then click on a menu option, you will receive the error:

 Uncaught TypeError: Cannot read property 'html' of undefined

**Comment by HugoGiraudel** [comment]
All I got is:

> Thank you for Visiting!
> I am currently working on a rebuild of my website. If you would like to contact me in regards to a project, email me at info@ryanwake.com

**Comment by ryanwake01** [comment]
If you go to http://ryanwake.com/gramacy/ This is where you will see the error I am getting.

**Comment by HugoGiraudel** [comment]
Still no error here.

**Comment by ryanwake01** [comment]
I created a screencast of the error I am getting. You can download the .mov file at http://ryanwake.com/gramacy/error.mov

This shows you exactly how/what is happening. The error that is occurring.

**Comment by tzi** [comment]
The error on Firefox is more explicit:

    TypeError: cache[url] is undefined | core-min.js (ligne 413, col. 24)
    $content    = utility.getContentById(containerId, cache[url].html);

I do not see the connection with the library `countdown.js`.
This come from `smoothState.js` or your use of this jQuery plugin.

Cheers,
Thomas.

**Comment by ryanwake01** [comment]
I. Am. an Idiot. I apologize for wasting your time. I linked to the wrong github project.

**Comment by HugoGiraudel** [comment]
No problem. Things happen. :)
